In [ ]:
import numpy as np
import pandas as pd
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.models import BayesianNetwork
from pgmpy.inference import VariableElimination

# Load and preprocess dataset
heartDisease = pd.read_csv('Medical Dataset.csv').replace('?', np.nan)
heartDisease[['ca', 'thal']] = heartDisease[['ca', 'thal']].apply(pd.to_numeric, errors='coerce')
heartDisease.dropna(inplace=True)

# Display sample instances and datatypes
print('Sample instances from the dataset are given below')
print(heartDisease.head())
print('\nAttributes and datatypes')
print(heartDisease.dtypes)

# Define the Bayesian Network structure and learn CPD using Maximum Likelihood Estimation
model = BayesianNetwork([('age', 'heartdisease'), ('gender', 'heartdisease'), ('exang', 'heartdisease'),
                         ('cp', 'heartdisease'), ('heartdisease', 'restecg'), ('heartdisease', 'chol')])
print('\nLearning CPD using Maximum likelihood estimators')
model.fit(heartDisease, estimator=MaximumLikelihoodEstimator)

# Inference with Bayesian Network
print('\nInferencing with Bayesian Network:')
HeartDiseasetest = VariableElimination(model)

# Queries
print('\n1. Probability of HeartDisease given evidence= restecg')
print(HeartDiseasetest.query(variables=['heartdisease'], evidence={'restecg': 1}))
print('\n2. Probability of HeartDisease given evidence= cp')
print(HeartDiseasetest.query(variables=['heartdisease'], evidence={'cp': 2}))


C:\Users\rajat\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Sample instances from the dataset are given below
   age  gender  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   63       1   1       145   233    1        2      150      0      2.3   
1   67       1   4       160   286    0        2      108      1      1.5   
2   67       1   4       120   229    0        2      129      1      2.6   
3   37       1   3       130   250    0        0      187      0      3.5   
4   41       0   2       130   204    0        2      172      0      1.4   

   slope   ca  thal  heartdisease  
0      3  0.0   6.0             0  
1      2  3.0   3.0             2  
2      2  2.0   7.0             1  
3      3  0.0   3.0             0  
4      1  0.0   3.0             0  

Attributes and datatypes
age               int64
gender            int64
cp                int64
trestbps          int64
chol              int64
fbs               int64
restecg           int64
thalach           int64
exang             int64
oldpeak         float64
slope

In [1]:
import pandas as pd

# Sample data
data = {
    "Feature1": [1, 4, 7, 10, 13, 16, 19, 22, 25, 28],
    "Feature2": [2, 5, 8, 11, 14, 17, 20, 23, 26, 29],
    "Feature3": [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
    "Target": [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv("4ds.csv", index=False)


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

def read_csv(file_path):
    data = pd.read_csv(file_path)
    print("Data read from CSV:\n", data.head())
    return data

def preprocess_data(data):
    le = LabelEncoder()
    for column in data.columns:
        if data[column].dtype == object:
            data[column] = le.fit_transform(data[column])
    print("Data after preprocessing:\n", data.head())
    return data

def build_ann(data):
    data = preprocess_data(data)
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    
    print("X_train:\n", X_train.head())
    print("y_train:\n", y_train.head())
    
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    print("X_train after scaling:\n", X_train[:5])
    print("X_test after scaling:\n", X_test[:5])
    
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
    mlp.fit(X_train, y_train)
    predictions = mlp.predict(X_test)
    
    print("Predictions:", predictions)
    print("Actual:", y_test.values)
    
    return accuracy_score(y_test, predictions)

# Example usage:
data = read_csv('4ds.csv')
accuracy = build_ann(data)
print("Accuracy:", accuracy)


Data read from CSV:
    Feature1  Feature2  Feature3  Target
0         1         2         3       0
1         4         5         6       1
2         7         8         9       0
3        10        11        12       1
4        13        14        15       0
Data after preprocessing:
    Feature1  Feature2  Feature3  Target
0         1         2         3       0
1         4         5         6       1
2         7         8         9       0
3        10        11        12       1
4        13        14        15       0
X_train:
    Feature1  Feature2  Feature3
0         1         2         3
7        22        23        24
2         7         8         9
9        28        29        30
4        13        14        15
y_train:
 0    0
7    1
2    0
9    1
4    0
Name: Target, dtype: int64
X_train after scaling:
 [[-1.54230764 -1.54230764 -1.54230764]
 [ 0.89553347  0.89553347  0.89553347]
 [-0.84578161 -0.84578161 -0.84578161]
 [ 1.5920595   1.5920595   1.5920595 ]
 [-0.14925558 -0.1

c:\Users\sagar\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
